"""
Sends scraped content (or just a company name, if that's all we have)
to Gemini and validates the response against the SalesBrief schema.

Strictness strategy:
1. System prompt demands JSON-only output matching an explicit schema.
2. Response is parsed and validated with Pydantic.
3. If parsing/validation fails, we retry ONCE with the raw error fed
   back to the model ("your last output was invalid, fix it").
4. If it still fails, we return None and the caller logs it as a failed lead
   rather than silently accepting garbage.
"""

import json
import os
import re

from dotenv import load_dotenv
import google.generativeai as genai
from google.api_core.exceptions import NotFound, ResourceExhausted
from pydantic import ValidationError

from models import SalesBrief

load_dotenv(dotenv_path=".env")
FREE_MODE = os.environ.get("FREE_MODE", "false").strip().lower() in {"1", "true", "yes"}
if not FREE_MODE:
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])
MODEL_CANDIDATES = [
    model.strip()
    for model in os.environ.get(
        "GEMINI_MODEL_CANDIDATES",
        "gemini-3-flash-preview,gemini-3.1-flash-lite,gemini-flash-lite-latest",
    ).split(",")
    if model.strip()
]

SYSTEM_PROMPT = """You are a B2B sales research assistant. You will be given \
raw scraped text from a company's website (or just a company name if no \
website content is available). Analyze it and respond with ONLY a single \
valid JSON object — no markdown fences, no commentary — matching exactly \
this schema:

{
  "company_name": string,
  "company_overview": string (1-3 sentences),
  "core_product_or_service": string,
  "target_customer": string,
  "is_b2b_lead": boolean,
  "b2b_reasoning": string (short justification),
  "sales_questions": [string, string, string] (exactly 3 specific questions),
  "notes": string or null (mention if data was limited/missing)
}

Be conservative: if the content doesn't give enough evidence to be sure this \
is a B2B lead, still make your best judgment call and explain why in \
b2b_reasoning. Do not invent specific facts (like revenue or employee count) \
that are not implied by the source content."""


def _local_analyze(lead_label: str, scraped_text: str | None, source_url: str | None = None) -> SalesBrief:
    text = scraped_text or lead_label or ""
    cleaned = re.sub(r"\s+", " ", text.strip())
    if not cleaned:
        cleaned = lead_label or "Unknown company"

    is_b2b = bool(re.search(r"\b(?:enterprise|business|B2B|corporate|teams|clients|organizations|companies|wholesale|solutions?)\b", cleaned, re.IGNORECASE))
    core_product_or_service = "Business software and services"
    target_customer = "Businesses and enterprise teams"
    company_name = lead_label if lead_label and not lead_label.startswith("http") else source_url or lead_label

    if scraped_text:
        if match := re.search(r"(?:offers|provides|delivers|builds|creates|helps|supports) ([^.\n]+)", cleaned, re.IGNORECASE):
            core_product_or_service = match.group(1).strip().rstrip(".")
        if re.search(r"\b(finance|marketing|sales|IT|human resources|operations|logistics)\b", cleaned, re.IGNORECASE):
            target_customer = "Corporate teams and departments"
        elif re.search(r"\b(consumers|customers|individuals|shoppers)\b", cleaned, re.IGNORECASE):
            target_customer = "Consumers and individual buyers"
        elif re.search(r"\b(businesses|companies|enterprises|organizations)\b", cleaned, re.IGNORECASE):
            target_customer = "Other businesses and organizations"

    if not is_b2b:
        target_customer = "Small businesses or consumers"

    b2b_reasoning = (
        "The description includes clear business-facing language and enterprise-use keywords."
        if is_b2b
        else "The description does not clearly indicate a business-only offering, so this is a best-guess classification."
    )

    questions = [
        f"What business challenge are you solving for your target customers with {core_product_or_service}?",
        f"How does your solution currently integrate with existing systems used by {target_customer.lower()}?",
        f"What metrics or outcomes do your {target_customer.lower()} care most about?",
    ]

    return SalesBrief(
        company_name=company_name,
        company_overview=f"{company_name} appears to provide {core_product_or_service.lower()} to {target_customer.lower()}.",
        core_product_or_service=core_product_or_service,
        target_customer=target_customer,
        is_b2b_lead=is_b2b,
        b2b_reasoning=b2b_reasoning,
        sales_questions=questions,
        source_url=source_url,
        notes="Generated by free local analysis. Accuracy is limited compared to Gemini." if FREE_MODE else "Generated by local fallback because Gemini was unavailable.",
    )


def _call_model(prompt: str) -> str:
    last_error = None
    for model_name in MODEL_CANDIDATES:
        print(f"[MODEL TRY] {model_name}")
        try:
            model = genai.GenerativeModel(model_name, system_instruction=SYSTEM_PROMPT)
            response = model.generate_content(prompt)
            return response.text.strip()
        except ResourceExhausted as e:
            print(f"[MODEL QUOTA] {model_name} exhausted, trying next model.")
            last_error = e
        except NotFound as e:
            print(f"[MODEL UNAVAILABLE] {model_name} not found, trying next model.")
            last_error = e
        except Exception as e:
            print(f"[MODEL ERROR] {model_name}: {e}")
            last_error = e

    if isinstance(last_error, ResourceExhausted):
        raise RuntimeError(
            "Gemini rate limit or quota has been reached. Set up billing for your Google Cloud project, reduce request volume, or choose a different model using GEMINI_MODEL_CANDIDATES."
        ) from last_error
    if isinstance(last_error, NotFound):
        raise RuntimeError(
            "The configured Gemini models are unavailable. Update GEMINI_MODEL_CANDIDATES to a currently supported model list."
        ) from last_error

    raise RuntimeError(
        "All model candidates failed. Check your API key, quota, or model availability."
    ) from last_error


def _strip_code_fences(text: str) -> str:
    """Gemini sometimes wraps JSON in ```json ... ``` even when told not to."""
    if text.startswith("```"):
        text = text.split("```")[1]
        text = text.removeprefix("json").strip()
    return text


def analyze_lead(lead_label: str, scraped_text: str | None, source_url: str | None = None) -> SalesBrief | None:
    """
    lead_label: the raw input (URL or company name) for context
    scraped_text: cleaned website text, or None if scraping failed/unavailable
    """
    if scraped_text:
        prompt = f"Lead: {lead_label}\n\nScraped website content:\n{scraped_text}"
    else:
        prompt = (
            f"Lead: {lead_label}\n\n"
            "No website content could be retrieved for this lead. "
            "Work from the name/description alone, and note the limitation."
        )

    if FREE_MODE:
        return _local_analyze(lead_label=lead_label, scraped_text=scraped_text, source_url=source_url)

    raw = _call_model(prompt)

    for attempt in range(2):  # first try + one retry
        try:
            cleaned = _strip_code_fences(raw)
            data = json.loads(cleaned)
            data["source_url"] = source_url
            return SalesBrief(**data)
        except (json.JSONDecodeError, ValidationError) as e:
            if attempt == 0:
                # One retry: tell the model exactly what went wrong
                retry_prompt = (
                    f"Your previous output was invalid: {e}\n\n"
                    f"Previous output was:\n{raw}\n\n"
                    "Return ONLY the corrected valid JSON object, nothing else."
                )
                raw = _call_model(retry_prompt)
            else:
                print(f"[FAILED] Could not get valid JSON for '{lead_label}': {e}")
                return None
    return None
